### ISSUE TITLE
When applying the terraform in the cloud shell getting errors for helm init

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/cloud-game-servers-examples#6]
Running the terraform apply in the cloud shell is printing out the following errors:

```
module.game-cluster-us-2.module.helm_agones.null_resource.helm_init (local-exec): Error: unknown command "init" for "helm"

module.game-cluster-us-2.module.helm_agones.null_resource.helm_init (local-exec): Did you mean this?
module.game-cluster-us-2.module.helm_agones.null_resource.helm_init (local-exec):       lint

module.game-cluster-us-2.module.helm_agones.null_resource.helm_init (local-exec): Run 'helm --help' for usage.
```

My Cloud shell instance is using Helm v3 & Agones v1.7+ is supporting Helm v3. The solution should be updated to be Helm 3 compatible.

```
helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by markmandel** [comment]
100% agreed - 1.6.0 expects Helm 2 to be installed locally:
https://1-6-0.agones.dev/site/docs/installation/terraform/ 

(Which it is not for cloud shell)

Upgrading this example to 1.7.0 and the helm3 packages will fix this.

**Comment by pooneh-m** [comment]
> (Which it is not for cloud shell)
> 

Thanks. The cloud Shell does not have Helm installed by default.

**Comment by markmandel** [comment]
Last time I tried it, Cloud Shell had Helm 3 installed by default.
