### ISSUE TITLE
Fail to run gen-certs.sh in mac

### ISSUE THREAD

**Issue by Yingxin-Jiang** [googleforgames/cloud-game-servers-examples#8]
In Mac, I got an error when running gen-certs.sh. I tried to uncomment the statements for Mac in gen-certs.sh, but it didn't help.

$ ./gen-certs.sh 
+ gcloud container clusters list '--format=value(name,zone)'
+ grep game-cluster
+ read -r line
+ cluster_setup game-cluster-eu-1 europe-west4-b
+ echo 'Setting up cluster: game-cluster-eu-1 europe-west4-b'
Setting up cluster: game-cluster-eu-1 europe-west4-b
+ gcloud container clusters get-credentials game-cluster-eu-1 --zone europe-west4-b
Fetching cluster endpoint and auth data.
kubeconfig entry generated for game-cluster-eu-1.
++ kubectl config current-context
+ CERT_FOLDER=./certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1
+ mkdir -p ./certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1
+ server_cert game-cluster-eu-1 europe-west4-b
+ echo 'Setting up server certs: game-cluster-eu-1 europe-west4-b'
Setting up server certs: game-cluster-eu-1 europe-west4-b
+ cat
+ kubectl apply -f -
clusterissuer.cert-manager.io/selfsigned unchanged
++ kubectl get services agones-allocator -n agones-system -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'
+ EXTERNAL_IP=34.91.208.135
+ cat
+ kubectl apply -f -
certificate.cert-manager.io/allocator-selfsigned-cert unchanged
+ TLS_CA_FILE=./certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/ca.crt
++ kubectl get secret allocator-tls -n agones-system '-ojsonpath={.data.ca\.crt}'
+ TLS_CA_VALUE=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2ekNDQWRPZ0F3SUJBZ0lRQ1YwOEtPcFc0K0E4MVdvN3k2N0ZVakFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFERXcwek5DNDVNUzR5TURndU1UTTFNQjRYRFRJd01EY3dOekl3TURFeE0xb1hEVEl3TVRBdwpOVEl3TURFeE0xb3dHREVXTUJRR0ExVUVBeE1OTXpRdU9URXVNakE0TGpFek5UQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMM1crZ1J4YUpXbkdaQ0ZHMEtsNHVteS83YjJLWGoxUGZTeFl1Tm0Kc2FJQkJPaEVTZGRnVDRCb3JGVXE0VGZ6WXIxOHZvNXkrSjRXUW0xMEtlSlRqeTlobEdRTzhwYng2V2NtYTZ2Rwp5dVJkMDR2OE5CRFU1THM1S2tOYlh1NWdEemlzUGx5dXJVY25SWGFDc2JTdlJUdkh0dUVBOWowZHpUVy9KU0RnCmpMemdwUFdhbG13aFl5MjUyNFN3UnJGZXpTd3A3WHdHYStZNmJJWWpiYStFV3VLUis5MkRUa1FLM3F3LzJQMW0Kd0taMyt5OUJEMC9CdWJzRHN6M2ViQUk0cWNacGUyYW1YQURSTXhCUmZUb3p5d2VmWTRlZiswTjhjSU9UUUMwawpBRVRTck5hOHcrdHJUY0xuUGp1ZFpTd0JBUVo3V3BaVWNNZ1J6cUd2MzFzOGloMENBd0VBQWFNeE1DOHdEZ1lEClZSMFBBUUgvQkFRREFnV2dNQXdHQTFVZEV3RUIvd1FDTUFBd0R3WURWUjBSQkFnd0JvY0VJbHZRaHpBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFNV1VUdlVjRGZoQXgxVVoxSWNja2IvTWVOSnZFZ2ZtZ2E1amdzRGx2cm15MApvVVBSR2FFdEw1blVFNzgyK3F1aURzK3pmZlRLT1lVeFhLdURaMnY4SWZ6ZGdDdXN2NG01UXh3cTJtcksxKzNqCms5Qk1aQ2VrK2lqQmd1WE9WSk5ZekNjblcxUUg2K0s0a2V6dEs0eWZXbHVlWnpwZnpNa3RvdXpkZDltbnJBUnQKZTk3VExDdVJrb2ViV1VlemJHbkpDSFBkdTR3YUFjd0dHL2F6bXJnZ3B5OVEzc0tWY2JKTEpjaU1iS1h2RUQzaApsemFXWGd1U2x0c1FPbjl1UnZISzlLckJnWDVicWdyRGNTOVBHcnhOayswSjFyQ1Q4TDNlMmpnNFQ4bkJHQ1NxCmh4L3lzWGJWNHljZEtYVTcwbjQvZmxQdVNDeXVncWNhVWlDYUlQa3ZIQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
+ echo LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2ekNDQWRPZ0F3SUJBZ0lRQ1YwOEtPcFc0K0E4MVdvN3k2N0ZVakFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFERXcwek5DNDVNUzR5TURndU1UTTFNQjRYRFRJd01EY3dOekl3TURFeE0xb1hEVEl3TVRBdwpOVEl3TURFeE0xb3dHREVXTUJRR0ExVUVBeE1OTXpRdU9URXVNakE0TGpFek5UQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMM1crZ1J4YUpXbkdaQ0ZHMEtsNHVteS83YjJLWGoxUGZTeFl1Tm0Kc2FJQkJPaEVTZGRnVDRCb3JGVXE0VGZ6WXIxOHZvNXkrSjRXUW0xMEtlSlRqeTlobEdRTzhwYng2V2NtYTZ2Rwp5dVJkMDR2OE5CRFU1THM1S2tOYlh1NWdEemlzUGx5dXJVY25SWGFDc2JTdlJUdkh0dUVBOWowZHpUVy9KU0RnCmpMemdwUFdhbG13aFl5MjUyNFN3UnJGZXpTd3A3WHdHYStZNmJJWWpiYStFV3VLUis5MkRUa1FLM3F3LzJQMW0Kd0taMyt5OUJEMC9CdWJzRHN6M2ViQUk0cWNacGUyYW1YQURSTXhCUmZUb3p5d2VmWTRlZiswTjhjSU9UUUMwawpBRVRTck5hOHcrdHJUY0xuUGp1ZFpTd0JBUVo3V3BaVWNNZ1J6cUd2MzFzOGloMENBd0VBQWFNeE1DOHdEZ1lEClZSMFBBUUgvQkFRREFnV2dNQXdHQTFVZEV3RUIvd1FDTUFBd0R3WURWUjBSQkFnd0JvY0VJbHZRaHpBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFNV1VUdlVjRGZoQXgxVVoxSWNja2IvTWVOSnZFZ2ZtZ2E1amdzRGx2cm15MApvVVBSR2FFdEw1blVFNzgyK3F1aURzK3pmZlRLT1lVeFhLdURaMnY4SWZ6ZGdDdXN2NG01UXh3cTJtcksxKzNqCms5Qk1aQ2VrK2lqQmd1WE9WSk5ZekNjblcxUUg2K0s0a2V6dEs0eWZXbHVlWnpwZnpNa3RvdXpkZDltbnJBUnQKZTk3VExDdVJrb2ViV1VlemJHbkpDSFBkdTR3YUFjd0dHL2F6bXJnZ3B5OVEzc0tWY2JKTEpjaU1iS1h2RUQzaApsemFXWGd1U2x0c1FPbjl1UnZISzlLckJnWDVicWdyRGNTOVBHcnhOayswSjFyQ1Q4TDNlMmpnNFQ4bkJHQ1NxCmh4L3lzWGJWNHljZEtYVTcwbjQvZmxQdVNDeXVncWNhVWlDYUlQa3ZIQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
+ base64 -D
+ kubectl get secret allocator-tls-ca -o json -n agones-system
+ jq '.data["tls-ca.crt"]="LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2ekNDQWRPZ0F3SUJBZ0lRQ1YwOEtPcFc0K0E4MVdvN3k2N0ZVakFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFERXcwek5DNDVNUzR5TURndU1UTTFNQjRYRFRJd01EY3dOekl3TURFeE0xb1hEVEl3TVRBdwpOVEl3TURFeE0xb3dHREVXTUJRR0ExVUVBeE1OTXpRdU9URXVNakE0TGpFek5UQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMM1crZ1J4YUpXbkdaQ0ZHMEtsNHVteS83YjJLWGoxUGZTeFl1Tm0Kc2FJQkJPaEVTZGRnVDRCb3JGVXE0VGZ6WXIxOHZvNXkrSjRXUW0xMEtlSlRqeTlobEdRTzhwYng2V2NtYTZ2Rwp5dVJkMDR2OE5CRFU1THM1S2tOYlh1NWdEemlzUGx5dXJVY25SWGFDc2JTdlJUdkh0dUVBOWowZHpUVy9KU0RnCmpMemdwUFdhbG13aFl5MjUyNFN3UnJGZXpTd3A3WHdHYStZNmJJWWpiYStFV3VLUis5MkRUa1FLM3F3LzJQMW0Kd0taMyt5OUJEMC9CdWJzRHN6M2ViQUk0cWNacGUyYW1YQURSTXhCUmZUb3p5d2VmWTRlZiswTjhjSU9UUUMwawpBRVRTck5hOHcrdHJUY0xuUGp1ZFpTd0JBUVo3V3BaVWNNZ1J6cUd2MzFzOGloMENBd0VBQWFNeE1DOHdEZ1lEClZSMFBBUUgvQkFRREFnV2dNQXdHQTFVZEV3RUIvd1FDTUFBd0R3WURWUjBSQkFnd0JvY0VJbHZRaHpBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFNV1VUdlVjRGZoQXgxVVoxSWNja2IvTWVOSnZFZ2ZtZ2E1amdzRGx2cm15MApvVVBSR2FFdEw1blVFNzgyK3F1aURzK3pmZlRLT1lVeFhLdURaMnY4SWZ6ZGdDdXN2NG01UXh3cTJtcksxKzNqCms5Qk1aQ2VrK2lqQmd1WE9WSk5ZekNjblcxUUg2K0s0a2V6dEs0eWZXbHVlWnpwZnpNa3RvdXpkZDltbnJBUnQKZTk3VExDdVJrb2ViV1VlemJHbkpDSFBkdTR3YUFjd0dHL2F6bXJnZ3B5OVEzc0tWY2JKTEpjaU1iS1h2RUQzaApsemFXWGd1U2x0c1FPbjl1UnZISzlLckJnWDVicWdyRGNTOVBHcnhOayswSjFyQ1Q4TDNlMmpnNFQ4bkJHQ1NxCmh4L3lzWGJWNHljZEtYVTcwbjQvZmxQdVNDeXVncWNhVWlDYUlQa3ZIQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"'
+ kubectl apply -f -
secret/allocator-tls-ca configured
+ client_cert game-cluster-eu-1 europe-west4-b
+ echo 'Setting up server certs: game-cluster-eu-1 europe-west4-b'
Setting up server certs: game-cluster-eu-1 europe-west4-b
+ KEY_FILE=./certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/client.key
+ CERT_FILE=./certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/client.crt
+ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/client.key -out ./certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/client.crt -subj /C=/ST=/L=/O=/OU=/CN=
Generating a 2048 bit RSA private key
...........+++
.....+++
writing new private key to './certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/client.key'
-----
end of string encountered while processing type of subject name element #5
problems making Certificate Request

**Comment by markmandel** [comment]
Did you replace the Linux commands with the Mac ones?

Also - not seeing any errors. Was there an error message?

**Comment by Yingxin-Jiang** [comment]
Yes, I replaced the Linux commands with the Mac ones. I think the error message is "problems making Certificate Request".

I checked the version of openssl. The default one in my Mac is LibreSSL. 
$ openssl version
LibreSSL 2.8.3

I installed OpenSSL with the following version and the issue was resolved. 
$ openssl version
OpenSSL 1.1.1g  21 Apr 2020

It seems the script works with OpenSSL not LibreSSL? If LibreSSL is the default openssl in Mac, should we consider to get the script work with LibreSSL?

**Comment by markmandel** [comment]
This is scripts that came from:
https://agones.dev/site/docs/advanced/allocator-service/

So if it needs fixing, it needs to come from there.

Since i have no access to a Mac, if you want it to work with LibreSSL -- pull requests are more than welcome :smile:

**Comment by Yingxin-Jiang** [comment]
Since LibreSSL is not OpenSSL, it's fair to say LibreSSL might not work. We can consider to support LibreSSL if other users have concerns and it becomes a priority.

**Comment by Yingxin-Jiang** [comment]
However, after I installed OpenSSL in mac and ran gen-certs.sh, allocate.sh returned the following error in mac. (The allocate.sh script does work in Linux.)

+ go run main.go --ip 34.91.133.2 --namespace default --key /Users/yingxin/go/src/googleforgames/cloud-game-servers-examples/terraform-4-cluster/allocation/certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/client.key --cert /Users/yingxin/go/src/googleforgames/cloud-game-servers-examples/terraform-4-cluster/allocation/certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/client.crt --cacert /Users/yingxin/go/src/googleforgames/cloud-game-servers-examples/terraform-4-cluster/allocation/certs/gke_yingxin-devconsole_europe-west4-b_game-cluster-eu-1/ca.crt --multicluster true
panic: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed

goroutine 1 [running]:
main.main()
	/Users/yingxin/go/src/agones.dev/agones/examples/allocator-client/main.go:75 +0x7b3
exit status 2

============================================================
The allocator logs show the following error message:

$ kubectl logs agones-allocator-898464d7b-5hjjp --namespace=agones-system 
...
{"message":"client cert /home/allocator/client-ca/client-ca.crt is installed","severity":"info","source":"main","time":"2020-08-20T06:25:20.270375209Z"}
{"message":"client cert /home/allocator/client-ca/client_trial.crt cannot be installed","severity":"error","source":"main","time":"2020-08-20T06:25:20.270421731Z"}

**Comment by pooneh-m** [comment]
It is the Game Servers reconciliation 1h delay, when there is a change with the cluster secrets: https://cloud.google.com/game-servers/docs/how-to/configuring-multicluster-allocation
